# Project: Flutter-base Taxi
# Purpose: Testing integration of Flutter & Google Maps
# Platforms:  Web, iOS and Android
# Authors: www.flutterbase.com

name: flutterbasetaxi
description: Flutterbase Demo Project - a simple Uber App clone.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^6.0.0
  provider: ^5.0.0
  cupertino_icons: ^1.0.2
  flutter_animarker: ^3.2.0
  google_maps_flutter_web: 0.3.2+1
  google_maps_flutter: ^2.1.1
  google_polyline_algorithm: ^3.1.0
  geolocator: ^8.0.1
  flutter_svg: ^1.0.3
  flutter_rating_bar: ^4.0.0
  lottie: ^1.2.2
  shimmer: ^2.0.0
  google_maps_webservice:
    git:
      url: https://github.com/YakivGalkin/google_maps_webservice

  uuid: ^3.0.5

  touch_indicator: ^2.0.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/markers/
    - assets/lottie/
